### ISSUE TITLE
no overwrite option

### ISSUE THREAD

**Issue by aoberoi** [mysticatea/cpx#12]
i'd be interested (and possibly enough to develop and send a PR) in an option that prevented existing files in the dest directory from being written over. is this something the project maintainers would be interested in?

my use case is that i have a directory where i've outputted babel compiled javascript files from my entire source directory. within my source directory i have files that are not compiled by babel, and therefore not in the destination. i'd like to copy those wholesale by running something like `cpx src build --no-overwrite` so that the compiled files are left untouched and the remaining source files are copied to be alongside the compiled counterparts.

**Comment by mysticatea** [comment]
Thank you for the request.
It seem to be convenience.
I like this idea.

**Comment by NitroBAY** [comment]
Well we still need a --no-overwrite option. The point of no overwrite is to NOT overwrite at all, if a file has the same name as a file about to be copy in the same folder of it you simply don't move the file. The --update option is not the same thing.
