### ISSUE TITLE
NPM install fails on 1.3.0

### ISSUE THREAD

**Issue by mc-suchecki** [mysticatea/cpx#15]
I think there is something wrong with the newest version of the package in NPM:

npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.8.0
npm ERR! path C:\Code\xxx\node_modules\cpx\bin\index.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Code\xxx\node_modules\cpx\bin\index.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Code\xxx\node_modules\cpx\bin\index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

When I change the version to 1.2.1 in package.json, everything seems to be ok.

**Comment by mysticatea** [comment]
ugha, sorry I'll fix ASAP

**Comment by mysticatea** [comment]
I published a fixed version.
Thank you.

**Comment by mc-suchecki** [comment]
Yup, seems to work now, thank you for very fast reaction!
