### ISSUE TITLE
Empty directories are not copied

### ISSUE THREAD

**Issue by littleli** [mysticatea/cpx#17]
Empty directories are not copied from source destination to target location

Example: `cpx 'static/**/*' 'dest' --verbose`

This at the moment causing me no issues as I don't need to copy empty directories but I believe it may cause issues to someone. I believe it's a good candidate for a command line option, something like: 

`cpx 'static/**/*' 'dest' --verbose --include-empty-dirs`

Or the other way around, by copying all directories by default and allow user to specify if he wants to avoid empty directories by an command line option.

**Comment by mysticatea** [comment]
Thank you for this issue.

`--include-empty-dirs` is good idea.
I would appreciate PRs since I don't have enough time to add a new feature now.

When I get time, I will do.

**Comment by mysticatea** [comment]
I released [v1.5.0](https://github.com/mysticatea/cpx/releases/tag/v1.5.0) with `--include-empty-dirs` option.
