### ISSUE TITLE
option to skip the first copy (only watch)

### ISSUE THREAD

**Issue by donthebike** [mysticatea/cpx#19]
Hi, nice package.
For the cpx.watch, it would be nice to be able to skip the first copy (if files are already in sync.) Maybe add an option to the watch command (nocopy)?

**Comment by mysticatea** [comment]
Thank you for this issue. I'm sorry for delay.

Interesting.
A new option of `watch` command sounds reasonable.
Maybe:

- CLI: `--no-initial` (which set `false` to `options.initialCopy`)
- Node API: `options.initialCopy` (default: `true`)

**Comment by donthebike** [comment]
Thanks, sounds great.
I would personally implement the default the other way:
- CLI: `--initial` (which set true to `options.initialCopy` )
- Node API: `options.initialCopy` (default: `false`)
but that is a matter of taste and I can image you maybe do not want to break backwards compatibility.

**Comment by mysticatea** [comment]
I released [v1.5.0](https://github.com/mysticatea/cpx/releases/tag/v1.5.0) with `--no-initial` option.
Sorry, I didn't want to make a breaking change for now.

**Comment by donthebike** [comment]
Great. no problem.
Many thanks.
