### ISSUE TITLE
Braces expansion glob for directory copies directories instead of files

### ISSUE THREAD

**Issue by gwagener** [mysticatea/cpx#30]
I tried the following
```
cpx {a,b}/* c/
```
expecting all the files from inside `a/` and `b/` to be copied into `c/`. Instead I ended up with `c/a/` and `c/b/`.

I'm not sure if this is a bug or my expectations are wrong.

**Comment by mysticatea** [comment]
I'm sorry that I overlooked notifications.

This is intentional.
This tool copies files as keeping the path from the common parent directory.
