### ISSUE TITLE
Is command line working on Windows? 

### ISSUE THREAD

**Issue by kkorus** [mysticatea/cpx#37]
I have installed cpx using `npm i cpx -D` but when I try to run it I got message `'cpx' is not recognized as an internal or external command`

**Comment by mysticatea** [comment]
Yes. I'm a Windows user.

`npm` does not install the packages into the location which is in PATH env variable if you didn't specify `--global` option. You can use the packages in npm-scripts or with long name such as `./node_modules/.bin/cpx`.

**Comment by kkorus** [comment]
I have realised that later, thanks @mysticatea
