### ISSUE TITLE
Include "dotfiles" together with normal files

### ISSUE THREAD

**Issue by kirillgroshkov** [mysticatea/cpx#45]
Currently I need to do 2 separate commands to copy a folder with subfolder AND include dotfiles (e.g `.gitignore`, `.editorconfig`)

Commands I'm doing: 

```
# Copy over WPWebStatic-files
yarn cpx './export/WPWebStatic-files/**/*' ./export/WPWebStatic
# Separate command for 'dotfiles' (would be nice to combine it with previous)
yarn cpx './export/WPWebStatic-files/.*' ./export/WPWebStatic
```

I'd like to figure a way to copy both in one command. Any tips?..

**Comment by ramesaliyev** [comment]
i think this should do the trick;
`yarn cpx './export/WPWebStatic-files/**/{*,.*}' ./export/WPWebStatic`

**Comment by kirillgroshkov** [comment]
@ramesaliyev it worked! Amazing! Thank you! Opensource is amazing!

**Comment by ramesaliyev** [comment]
You're very welcome, and yeah, it is :)
