### ISSUE TITLE
npm audit issue

### ISSUE THREAD

**Issue by ringodotnl** [mysticatea/cpx#48]
When running npm audit we get a issue on:
cpx > chokidar > anymatch > micromatch > braces 

Would it be possible to update the version ?

Cheers,
Ringo.

**Comment by danielfigueiredo** [comment]
First of all thanks for this great library, really easy to use and amazing. Watcher mode is also cool
On this issue, this is currently the only warning I get and is blocking my CI to run smoothly. Do you folks by any chance have a plan to fix this? 

Manually adding a more recent version of `braces` doesn't remove the warning, I think NPM looks at your package.json definition

**Comment by danielfigueiredo** [comment]
Duplicate of https://github.com/mysticatea/cpx/issues/47

**Comment by TwitchBronBron** [comment]
Any update on when this will get fixed?

**Comment by kayvanbree** [comment]
Looks like the last commit was on [June 26, 2018](https://github.com/mysticatea/cpx/commits/master). I think we might not be getting a fix... @mysticatea do you still maintain this repository?

**Comment by TidyIQ** [comment]
@mysticatea ?

**Comment by marcos-abreu** [comment]
The "chokidar" dependency was removed with this commit (https://github.com/mysticatea/cpx/commit/0c7edde7c4cb342cb57c08ea3ebceb9ed7574bf7).

So I guess is just a question of issuing a new release of the package.

**Comment by takahashi-jiec** [comment]
Please release a new version of the package.

npm audit

| Low | Regular Expression Denial of Service |
|---|---|
| Package | braces |
| Patched in | >=2.3.1 |
| Dependency of | cpx |
| Path | cpx > chokidar > anymatch > micromatch > braces |
| More info | https://npmjs.com/advisories/786 |

**Comment by nicwaller** [comment]
I switched to [@deboxsoft/cpx](https://www.npmjs.com/package/@deboxsoft/cpx) on npm ([nurdiansyah/cpx](https://github.com/nurdiansyah/cpx) on GitHub) because this package is no longer being maintained/released. That current version passes `npm audit`. 🎉
