### ISSUE TITLE
./ paths don't work

### ISSUE THREAD

**Issue by k88hudson** [mysticatea/cpx#5]
Not sure if this is intended but the following doesn't work:

```
cpx \"./src/static/**/*\" ./www
```

If you remove the dot slashes it works fine.  I will get a better STR for this later.

**Comment by mysticatea** [comment]
Thank you for the report.

I have an old MacBook in a closet, so I will fix with using it.

**Comment by mysticatea** [comment]
Umm, I tried to add a test, but I could not reproduce.

```js
execSync("node lib/command.js \"./test-ws/**/*\" ./test-ws2");
```

It works.
Do you have idea?

----
Mac OS X 10.8.3 / Windows 7 64bit / Linux (Travis)
Node 0.10 / 0.12

**Comment by k88hudson** [comment]
Hm, you're right. Sorry about that!

I did notice a couple of tests failing on OSX, could be related to that... I will file as a separate issue.
