### ISSUE TITLE
Tests are failing on master due to eslint

### ISSUE THREAD

**Issue by k88hudson** [mysticatea/cpx#8]
Tests are failing with the following output as of `eslint v0.21.1` (on Linux/travis, Mac OSX)

```
src/cpx.js
  71:6  error  Cpx is already declared in the upper scope  no-shadow

src/queue.js
  17:6  error  Queue is already declared in the upper scope  no-shadow

✖ 2 problems (2 errors, 0 warnings)
```

Issue is filed on eslint here https://github.com/eslint/eslint/issues/2545, looks like a fix is incoming here https://github.com/eslint/eslint/pull/2547

Would you maybe like to lock down the version of eslint to `v0.21.0`? 

(Tested on Mac OSX 10.10.2, node v0.12.2, npm 2.7.4)

**Comment by mysticatea** [comment]
Yeah, let lock to `v0.21.0`.
